algoritmo "004_FORMATAÇÃO"
var

   n1, n2 : inteiro
   r1, r2 : real

inicio

      n1<-586
      n2<-577725
      r1<-17.8
      r2<-1.987
      
      //escreval(n1:9:2)
      //escreval(n2:6)
      
      escreval (r1:7:1)
      escreval (r2:9:3)

      //sendo que:
      //r1 é a variável
      //o número depois do primeiro sinal de " : "
      //"dois pontos" o número de espaços
      //o número depois do segundo sinal de " : "
      //conta as casas decimais


fimalgoritmo