algoritmo "013_estruturas de repetição_REPITA_ATÉ_v1"
var

   i : inteiro //variável para a estrutura de repetição (iteração)

inicio

      //repetição enquanto () faca
      i<-1
      
      enquanto (i<11) faca
               i<-i+1
               escreva(i:4)
      fimEnquanto
      escreval
      escreval
      escreval("* * * * *")
      escreval
      //repetição repita () ate

      //i<-100

      repita
            i<-i+1
            escreva(i:4)
      ate i>10

fimalgoritmo