algoritmo "014_L03_EX_01_v3_fatorial"

//faça um algoritmo que leia um número inteiro e calcule seu fatorial

var

   n1, i : inteiro
   fatorial : inteiro

inicio

      n1<-6
      fatorial<-1

      para i de n1 ate 1 passo -1 faca
           escreva(i, " x ", fatorial)
           fatorial<-fatorial*i
           escreva(" = ", fatorial)
           escreval



      fimPara

      //escreval(i)
      //escreva("Fatorial de ", n1, " é ", fatorial)
fimalgoritmo